cpd_period_yrs = 3
cpd_hrs_total = 150
cpd_hrs_total_desc = "Your CPD records must document a minimum of 150 hours of structured CPD over a three-year period"
cpd_hrs_risk = 10 
cpd_hrs_risk_desc = "at least 10 hours must cover risk management"
cpd_hrs_area = 50
cpd_hrs_area_desc = "at least 50 hours must relate to your area(s) of practice"
cpd_hrs_business = 15
cpd_hrs_business_desc = "at least 15 hours must address business and management skills"
activity_types = [
    "Conference",
    "Exhibition",
    "Meeting",
    "Mentoring session",
    "Online study",
    "Other",
    "Presentation/paper preparation",
    "Private study - book/manual",
    "Private study - journal/magazine",
    "Private study - research/web articles",
    "Private study - audio/podcast",
    "Seminar",
    "Technical presentation",
    "Technical site visit",
    "Tertiary study",
    "Training course/session - external",
    "Training course/session - workplace",
    "Volunteer activity",
    "Workshop",
]

[cpd_types]
    [cpd_types.A]
        desc = "Tertiary Education"
        desc_long = "Any tertiary course taken either as an individual course or for a formal post-graduate award"

    [cpd_types.B]
        desc= "Industry Education"
        desc_long= "Short courses, workshops, seminars and discussion groups, conferences, technical inspections and technical meetings"
        
    [cpd_types.C]
        desc= "Workplace Learning"
        desc_long = "Learning activities in the workplace that extend competence in the area of practice"
        limit = 75
        conditions = "A maximum of 75 hours of your total CPD"
    
    [cpd_types.D]
        desc= "Private Study"
        desc_long = "Private study which extends your knowledge and skills"
        limit= 35
        conditions= "The total claimable hours for Type III and IV combined are 110 hours"

    [cpd_types.E]
        desc= "Service"
        desc_long= "Service to the engineering profession"
        limit= 50
        conditions= "A maximum of 50 hours of your total CPD"

    [cpd_types.F]
        desc= "Presentations and papers"
        desc_long= "The preparation and presentation of material for courses, conferences, seminars and symposia"
        conditions= "Up to 45 hours per paper"

    [cpd_types.G]
        desc= "Industry Involvement (for academics)"
        desc_long= "Practitioners employed in tertiary teaching or academic research"
        conditions= "Chartered members employed in tertiary teaching and/or academic research must be able to demonstrate a minimum of 40 hours of industry involvement"

    [cpd_types.H]
        desc= "Other"
        desc_long= "Any other structured activities not covered by I to VI above that meet the objectives of the CPD policy"
        conditions= "Documentary evidence and a clear justification will be necessary"
